highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://juliorimo.github.io/vitae/
author: Julio Rivas

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Julio Rivas's Resume
name: Julio Rivas
email: julio@lualabs.com
email_full: mailto:julio@lualabs.com
website: github.io/juliorimo
website_full: https://juliorimo.github.io
github: juliorimo
twitter: juliorimo
tel: +34 666 371 387
tel_full: tel:+34666371387
google_maps: 'https://www.google.es/maps/place/Madrid'
address: 
postcode: 
city: Madrid
country: Spain
google_analytics: UA-89201130-1

# needed for travis-ci build
exclude: [vendor]
